server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://rm-bp179d713uc419em0ho.mysql.rds.aliyuncs.com/community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: community
    password: Zh1997090610
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.exmail.qq.com
    username: service@hcven.cn
    password: s2jCUR8QMNB5K5Qp
    default-encoding: utf-8