dubbo:
  application:
    name: community-user # 服务名
  registry:
    address: redis://127.0.0.1:6379 # 注册中心地址
  protocol:
    name: dubbo # 指定通信协议
    port: 20880 # 通信端口  这里指的是与消费者间的通信协议与端口
  provider:
    timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
    retries: 3 # 重试3次
    delay: -1

spring:
  profiles:
    active: prd
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1

logging:
  #  config: ./log4j2-spring.xml
  level:
    com.hcven: trace

mybatis:
  configuration:
    cache-enabled: true
